# Generated by Django 6.0.6 on 2026-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_add_analysis_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
